#!/bin/sh

set -x

###### 1. Bound states ######

./Ar_bound_DF


###### 2. Continuum state: d-wave, kappa = 2 ######

# Add one additional orbital with just one electron to CSFs list.
# For d-wave and kappa = 2, we use 4d(1,i) coupled to J = 3/2.
rcsfgenerate << S1
*
3         ! Argon
4d(1,i)   ! Additional d-wave electron

4d
3,3       ! J=3/2
0         ! No excitations
n
S1

mv rcsf.out rcsf.inp

rangular << S2
y
S2

# Initial estimates of radial wave functions.
# Use previosly calculated functions for bound states (DF.w),
# and any other method for the addidtional (continuum) orbital.
# Here, dedicated method (5), intended for continuum orbitals only, is used
# (but any other should also work).
rwfnestimate << S3
y
1
DF.w
*
5
*
S3

# Now run rmcdhf for continuum wave function calculation.
# Now, use the polarization potential given in numerical form
# and read from the 'vpol' file.
# Bear in mind, that grid should be long enough, and dense enough
# to obtain "nice-looking" function.
# Most important switches/answers are described below.
rmcdhf << S4
n          ! Do not use default settings
n
y          ! Enable continuum orbital calculations
0.0449988  ! Continuum electron energy (hartree)
3          ! Include polarization from the 'vpol' file
y          ! Normalize calculated continuum wave function
y          ! Change defaut speed of light or radial grid parameters
n
y          ! Revise default radial grid parameters
5.2631578947368416E-008   ! New RNT
5.0E-2     ! New H
0.2        ! New HP; use non-zero value to force the lin-log grid
5000       ! New N; Use as big as possible
n
999
n
1
S4
