#!/bin/sh

set -x

###### 2. Continuum state: s-wave, kappa = -1 ######

# Add one additional orbital with just one electron to CSFs list.
# It will be treated as continuum electron during the SCF procedure.
# Principal quantum number will be ignored,
# kappa will be determined from the subshell designation.
# E.g. 4s(1,i), coupled to J = 1/2 means s-wave electron of kappa = -1
#      4p(1,i), coupled to J = 1/2 means p-wave electron of kappa =  1
#      4p(1,i), coupled to J = 3/2 means p-wave electron of kappa = -2
#      4d(1,i), coupled to J = 3/2 means d-wave electron of kappa =  2
#      4d(1,i), coupled to J = 5/2 means d-wave electron of kappa = -3
#      etc.
rcsfgenerate << S1
*
3         ! Argon
4s(1,i)   ! Additional s-wave electron

4s
1,1       ! J=1/2
0         ! No excitations
n
S1

mv rcsf.out rcsf.inp

rangular << S2
y
S2

# Initial estimates of radial wave functions.
# Use previosly calculated functions for bound states (Ar.w),
# and any other method for the addidtional (continuum) orbital.
# Here, dedicated method (5), intended for continuum orbitals only, is used
# (but any other should also work).
rwfnestimate << S3
y
1
Ar.w
*
5
*
S3

# Now run rmcdhf for continuum wave function calculation.
# Here, use the default parameters of polarization potential.
# Bear in mind, that grid should be long enough, and dense enough
# to obtain "nice-looking" function.
# Most important switches/answers are described below.
rmcdhf << S4
n          ! Do not use default settings
n
y          ! Enable continuum orbital calculations
0.1        ! Continuum electron energy (hartree)
1          ! Include polarization potential with default parameters
n          ! Do not normalize calculated continuum wave function
y          ! Change defaut speed of light or radial grid parameters
n
y          ! Revise default radial grid parameters
1.0E-007   ! New RNT
5.0E-2     ! New H
0.2        ! New HP; use non-zero value to force the lin-log grid
5000       ! New N; Use as big as possible
n
999
n
1
S4
