#!/bin/sh

set -x

###### 3. Continuum state: zero-energy wave for scattering length calculations ######

# Add one additional orbital with just one electron to CSFs list.
# Since we would like to calculate scattering length,
# we add the s-wave electron, coupled to final J = 1/2,
# giving kappa = -1 (principal quantum number is ignored).
rcsfgenerate << S1
*
3         ! Argon
4s(1,i)   ! Additional s-wave electron

4s
1,1       ! J=1/2 => kappa = -1
0         ! No excitations
n
S1

mv rcsf.out rcsf.inp

rangular << S2
y
S2

# Initial radial wave functions estimates.
# Use previosly calculated rwf for bound states (Ar.w),
# and any other method for the addidtional (continuum) orbital.
rwfnestimate << S3
y
1
Ar.w
*
5
*
S3

# Now run rmcdhf for scattering length calculations.
# This is accomplished by forcing zero energy of the continuum electron.
# Use manually entered parameters of polarization potential.
# The further the grid extends from the nucleus, the better accuracy (in general).
rmcdhf << S4
n          ! Do not use default settings
n
y          ! Enable continuum orbital calculations
0.0        ! Continuum electron energy (hartree, negative), zero for scattering length
2          ! Include polarization potential with default parameters
11.083     ! Static dipole polarizability
7.76       ! <r0^3> cut-off
0.14       ! Static quadrupole polarizability
65.74      ! <r0^5> cut-off
n          ! Do not normalize calculated continuum wave function
y          ! Change defaut speed of light or radial grid parameters
n
y          ! Revise default radial grid parameters
1.0E-007   ! New RNT
5.0E-2     ! New H
1.0        ! New HP; use non-zero value to force the lin-log grid
5000       ! New N; Use as big as possibe
n
999
n
1
S4
