#!/bin/sh

set -x

###### Continuum state ######

# Strontium ground configuration is the Krypton core + two 5s electrons.
# One additional orbital with one electron is added - it will be treated as continuum electron.
# Here, 6s(1,i), coupled to J = 1/2 means 1 electron of kappa = -1 (s-wave).
rcsfgenerate << S6
*
4                ! Krypton core
5s(2,i)6s(1,i)   ! Strontium with additional s-wave electron

6s
1,1              ! J=1/2
0
n
S6

mv rcsf.out rcsf.inp

rangular << S7
y
S7

# Use previously calculated and saved file for bound states,
# and any other method for continuum orbital.
rwfnestimate << S8
y
1
Sr.w
*
5
*
S8

# Run rmcdhf for continuum wave function calculation.
# Use non-default, user-entered parameters of polarization potential
# (for demonstration only).
rmcdhf << S9
n
n
y        ! Continuum orbital calculations
-0.0     ! Continuum electron energy (hartree, negative)
1        ! Polarization potential, manually entered parameters
n        ! Normalization
y
n
y
1.0E-007
5.0E-2
8.0      ! Enable long Lin-log grid
5000
n
999
n
1
S9
